Removed an unnecessary exclusion of the code portion that was suspected to cause C# compiler error CS0570 in a consuming project.
The error was actually caused by the issue in .NET SDK 10.0.100-preview.4 that dropped the use of "specialname" IL flag for extension method implementations of static types.